# Generated by Django 5.0.6 on 2024-05-26 00:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('ID_CLIENTE', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NOME_FANTASIA', models.CharField(max_length=255)),
                ('RAZAO_SOCIAL', models.CharField(max_length=255)),
                ('CNPJ', models.CharField(max_length=14)),
                ('STATUS', models.CharField(max_length=10)),
                ('CNAE_PRINCIPAL_DESCRICAO', models.CharField(max_length=255)),
                ('CEP', models.CharField(max_length=11)),
                ('DATA_ABERTURA', models.DateField()),
                ('DDD', models.IntegerField(default=0)),
                ('TELEFONE', models.CharField(max_length=14)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('TIPO_LOGRADOURO', models.CharField(max_length=20)),
                ('LOGRADOURO', models.CharField(max_length=255)),
                ('NUMERO', models.CharField(max_length=20)),
                ('COMPLEMENTO', models.CharField(max_length=255)),
                ('BAIRRO', models.CharField(max_length=255)),
                ('MUNICIPIO', models.CharField(max_length=150)),
                ('UF', models.CharField(max_length=2)),
                ('FOTO', models.TextField()),
                ('LIBERADO_SISTEMA', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='detalhes_usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_USUARIO', models.ImageField(default=0, upload_to='')),
                ('ID_EMPRESA', models.UUIDField()),
                ('NM_USUARIO', models.CharField(max_length=255)),
                ('FOTO', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('ID_EMPRESA', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NOME_FANTASIA', models.CharField(max_length=255)),
                ('RAZAO_SOCIAL', models.CharField(max_length=255)),
                ('CNPJ', models.CharField(max_length=14)),
                ('STATUS', models.CharField(max_length=10)),
                ('CNAE_PRINCIPAL_DESCRICAO', models.CharField(max_length=255)),
                ('CEP', models.CharField(max_length=11)),
                ('DATA_ABERTURA', models.DateField()),
                ('DDD', models.IntegerField(default=0)),
                ('TELEFONE', models.CharField(max_length=14)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('TIPO_LOGRADOURO', models.CharField(max_length=20)),
                ('LOGRADOURO', models.CharField(max_length=255)),
                ('NUMERO', models.CharField(max_length=20)),
                ('COMPLEMENTO', models.CharField(max_length=255)),
                ('BAIRRO', models.CharField(max_length=255)),
                ('MUNICIPIO', models.CharField(max_length=150)),
                ('UF', models.CharField(max_length=2)),
                ('LOGOMARCA', models.TextField()),
                ('LIBERADO_SISTEMA', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='formas_de_pagamento',
            fields=[
                ('ID_FORMAPGTO', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('NM_FORMAPGTO', models.CharField(max_length=155)),
                ('ATIVO', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='itemcliente',
            fields=[
                ('ID_ITEM', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ID_CLIENTE', models.UUIDField()),
                ('ARQUIVO_BASE64', models.TextField()),
                ('DATA_INCLUSAO', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='produtos',
            fields=[
                ('ID_PRODUTO', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('NM_PRODUTO', models.CharField(max_length=155)),
                ('ATIVO', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicos',
            fields=[
                ('ID_SERVICO', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('NM_SERVICO', models.CharField(max_length=155)),
                ('ATIVO', models.BooleanField(default=True)),
            ],
        ),
    ]
