# Generated by Django 5.0.6 on 2024-05-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='ID_EMPRESA',
            field=models.UUIDField(default=0),
        ),
        migrations.AddField(
            model_name='formas_de_pagamento',
            name='ID_EMPRESA',
            field=models.UUIDField(default=0),
        ),
        migrations.AddField(
            model_name='produtos',
            name='ID_EMPRESA',
            field=models.UUIDField(default=0),
        ),
        migrations.AddField(
            model_name='servicos',
            name='ID_EMPRESA',
            field=models.UUIDField(default=0),
        ),
    ]
