# Generated by Django 5.0.6 on 2024-05-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporion', '0002_clientes_id_empresa_formas_de_pagamento_id_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='operadoras',
            fields=[
                ('ID_OPERADORA', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('NOME_FANTASIA', models.CharField(max_length=255)),
                ('RAZAO_SOCIAL', models.CharField(max_length=255)),
                ('CNPJ', models.CharField(max_length=14)),
                ('STATUS', models.CharField(max_length=10)),
                ('CNAE_PRINCIPAL_DESCRICAO', models.CharField(max_length=255)),
                ('CEP', models.CharField(max_length=11)),
                ('DATA_ABERTURA', models.DateField()),
                ('DDD', models.IntegerField(default=0)),
                ('TELEFONE', models.CharField(max_length=14)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('TIPO_LOGRADOURO', models.CharField(max_length=20)),
                ('LOGRADOURO', models.CharField(max_length=255)),
                ('NUMERO', models.CharField(max_length=20)),
                ('COMPLEMENTO', models.CharField(max_length=255)),
                ('BAIRRO', models.CharField(max_length=255)),
                ('MUNICIPIO', models.CharField(max_length=150)),
                ('UF', models.CharField(max_length=2)),
                ('LOGOMARCA', models.TextField()),
                ('LIBERADO_SISTEMA', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('ID_VENDA', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ID_EMPRESA', models.UUIDField(default=0)),
                ('ID_PRODUTO', models.IntegerField(default=0)),
                ('NM_PRODUTO', models.CharField(max_length=155)),
                ('ID_SERVICO', models.IntegerField(default=0)),
                ('NM_SERVICO', models.CharField(max_length=155)),
                ('ID_FORMAPGTO', models.IntegerField(default=0)),
                ('NM_FORMAPGTO', models.CharField(max_length=155)),
                ('ID_CLIENTES', models.UUIDField(default=0)),
                ('NM_CLIENTE', models.CharField(max_length=155)),
                ('ID_OPERADORA', models.IntegerField(default=0)),
                ('NM_OPERADORA', models.CharField(max_length=155)),
                ('VR_TOTAL', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('VR_TAXAS', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('VR_DESCONTO', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('VR_ABATIMENTOS', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('PORCENTAGEM_COMISSAO', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('VR_COMISSAO', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('VR_ENTRADA', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('VR_PARCELADO', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('VR_SALDO', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('NR_RESERVA', models.CharField(default='0', max_length=30)),
                ('DT_EMBARQUE', models.DateField()),
                ('DT_RETORNO', models.DateField()),
                ('REEMBOLSO', models.BooleanField(default=False)),
                ('COMISSAO_RECEBIDA', models.BooleanField(default=False)),
                ('DT_PGTO_COMISSAO', models.DateField()),
                ('TIPO_RECEBIMENTO', models.CharField(default='0', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='DADOS_BANCARIOS',
            field=models.CharField(default='Não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='DADOS_BANCARIOS',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
