# Generated by Django 5.0.6 on 2024-05-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporion', '0003_operadoras_vendas_clientes_dados_bancarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='DATA_CANCELAMENTO',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='DATA_VENDA',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcliente',
            name='ID_CLIENTE',
            field=models.UUIDField(default=0),
        ),
    ]
