# Generated by Django 5.0.6 on 2024-05-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporion', '0004_vendas_data_cancelamento_vendas_data_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhes_usuarios',
            name='ID_USUARIO',
            field=models.IntegerField(default=0),
        ),
    ]
