# Generated by Django 5.0.6 on 2024-06-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporion', '0006_clientes_cnae_principal_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='DT_EMBARQUE',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='DT_PGTO_COMISSAO',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='DT_RETORNO',
            field=models.DateField(null=True),
        ),
    ]
