# Generated by Django 5.0.6 on 2024-06-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporion', '0007_alter_vendas_dt_embarque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='MOTIVO_CANCELAMENTO',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendas',
            name='STATUS',
            field=models.BooleanField(default=False),
        ),
    ]
